# Make name error handler with built in exceptions

x=9
y=0
try:
    print(z)
except NameError :
    print("Error in name")
except ValueError :
    print("error in value")
print(x)
